version: "3.7"

services:
  mongodb:
    image: mongo:6.0.6
    container_name: 'mongo'
    restart: always
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand('ping').ok"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - backend_services

  order-service:
    image: lolaakin/order-service:latest  # Image for order-service
    container_name: 'order-service'
    restart: always
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "wget", "-O", "/dev/null", "-q", "http://order-service:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      - ORDER_QUEUE_HOSTNAME=my-eventbus-8915.servicebus.windows.net
      - ORDER_QUEUE_USERNAME=RootManageSharedAccessKey
      - ORDER_QUEUE_PASSWORD=HLF3Z+u8+fNAbr5THN0iRJ1PLby2GGObJ+ASbCfceXI=
      - ORDER_QUEUE_NAME=orders
      - ORDER_QUEUE_PORT=5671
      - ORDER_QUEUE_TRANSPORT=tls
      - USE_WORKLOAD_IDENTITY_AUTH=false
      - ORDER_DB_URI=mongodb://mongodb:27017
      - ORDER_DB_NAME=orderdb
      - ORDER_DB_COLLECTION_NAME=orders
    networks:
      - backend_services

  virtual-customer:
    # image: lolaakin/virtual-customer:latest  # Image for virtual-customer
    image: ramymohamed/virtual-customer-l8:latest
    container_name: 'virtual-customer'
    restart: always
    environment:
      - ORDER_SERVICE_URL=http://order-service:3000/
      - ORDERS_PER_HOUR=60
    networks:
      - backend_services
    depends_on:
      order-service:
        condition: service_healthy

networks:
  backend_services:
    driver: bridge
